/**
 * SMART.i 파일 생성기 테스트 스크립트
 * Node.js 환경에서 실행하여 생성된 파일 내용을 확인
 */

// ES module이 아니므로 require 사용
const fs = require('fs');
const path = require('path');

// 테스트용 가상 스토어 데이터
const mockFlowData = {
    nodes: [
        {
            id: "pipe_001",
            type: "node",
            position: { x: 100, y: 100 },
            data: {
                label: "Main Pipe",
                componentType: "PIPE",
                componentProp: {
                    numberOfVolumes: 5,
                    xAreaTable: [
                        { volumeNumber: 1, area: 0.30 },
                        { volumeNumber: 2, area: 0.30 },
                        { volumeNumber: 3, area: 0.30 },
                        { volumeNumber: 4, area: 0.30 },
                        { volumeNumber: 5, area: 0.30 }
                    ],
                    xLengthTable: [
                        { volumeNumber: 1, length: 1.0 },
                        { volumeNumber: 2, length: 1.0 },
                        { volumeNumber: 3, length: 1.0 },
                        { volumeNumber: 4, length: 1.0 },
                        { volumeNumber: 5, length: 1.0 }
                    ],
                    verticalAngleTable: [
                        { volumeNumber: 1, verticalAngle: 0.0 },
                        { volumeNumber: 2, verticalAngle: 0.0 },
                        { volumeNumber: 3, verticalAngle: 0.0 },
                        { volumeNumber: 4, verticalAngle: 0.0 },
                        { volumeNumber: 5, verticalAngle: 0.0 }
                    ]
                }
            }
        },
        {
            id: "volume_001",
            type: "node", 
            position: { x: 300, y: 100 },
            data: {
                label: "Test Volume",
                componentType: "SNGLVOL",
                componentProp: {
                    area: 1.0,
                    length: 2.0,
                    volume: 2.0,
                    pressure: 1.5e6,
                    temperature: 573.15
                }
            }
        },
        {
            id: "inlet_001",
            type: "node",
            position: { x: 50, y: 100 },
            data: {
                label: "Inlet Boundary",
                componentType: "TMDPVOL",
                componentProp: {
                    area: 0.5,
                    length: 1.0,
                    timeTable: [
                        { time: 0.0, pressure: 1.6e6, temperature: 573.15, quality: 0.0 },
                        { time: 1000.0, pressure: 1.6e6, temperature: 573.15, quality: 0.0 }
                    ]
                }
            }
        }
    ],
    edges: [
        {
            id: "edge_001",
            source: "inlet_001",
            target: "pipe_001",
            data: { area: 0.30 }
        },
        {
            id: "edge_002", 
            source: "pipe_001",
            target: "volume_001",
            data: { area: 0.30 }
        }
    ]
};

// 간단한 SmartFileGenerator 클래스 모의 구현
class TestSmartFileGenerator {
    constructor() {
        this.cardCounter = 100;
        this.componentCounter = 100;
    }

    generateSmartFile(flowData) {
        const { nodes, edges } = flowData;
        
        let output = this.generateHeader();
        output += this.generateControlCards();
        output += this.generateTimeCards();
        output += this.generateMonitoringCards(nodes);
        output += this.generateTripCards();
        output += this.generateHydrodynamicComponents(nodes, edges);
        output += this.generateEndCard();
        
        return output;
    }

    generateHeader() {
        const date = new Date();
        const dateStr = date.toLocaleDateString('ko-KR');
        
        return `*===*===*==*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*
=             SMART365 Steady-State Input Deck for MARS-KS T/H Code             =
*===*===*==*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*
*
* Generated by System Editor on ${dateStr}
* 🤖 Generated with Claude Code (https://claude.ai/code)
*
*==============================================================================*
* Miscellaneous Control Cards                                                 *
*==============================================================================*
`;
    }

    generateControlCards() {
        return `*------------------------------------------------------------------------------*
* Card 100 : Problem Type and Options                                          *
*------------------------------------------------------------------------------*
*     type      options
100   new       transnt
*
*------------------------------------------------------------------------------*
* Card 101 : Input Check and Run Option                                        *
*------------------------------------------------------------------------------*
*     option
101   run
*
*------------------------------------------------------------------------------*
* Card 102 : Unit Selection                                                    *
*------------------------------------------------------------------------------*
*     input     output
102   si        si
*
*------------------------------------------------------------------------------*
* Card 110 : Noncondensable Gas Species                                        *
*------------------------------------------------------------------------------*
*     gas type
110   nitrogen
*
`;
    }

    generateTimeCards() {
        return `*==============================================================================*
* Time Step Control Cards                                                      *
*==============================================================================*
*
*     time  min-dt    max-dt    edit  minor   major    restart
200   0.0
201   100.0  1.0e-8   0.001    00019  1000    10000    100000
*
`;
    }

    generateMonitoringCards(nodes) {
        let output = `*==============================================================================*
* Minor Edit Data                                                              *
*==============================================================================*
*
`;
        
        let cardNum = 301;
        let groupNum = 1;
        
        nodes.forEach(node => {
            if (node.data?.componentType) {
                const componentId = this.getComponentId(node.id);
                output += `${cardNum}  p        ${componentId}010000   13.e6     17.e6     ${groupNum}     1     *${node.data.label || node.id} pressure\n`;
                cardNum++;
                groupNum++;
            }
        });

        return output;
    }

    generateTripCards() {
        return `*==============================================================================*
* Input Trip Data                                                              *
*==============================================================================*
*
401  time   0   gt   null     0     1.0e6    l  -1.0   "Always false"
*
`;
    }

    generateHydrodynamicComponents(nodes, edges) {
        let output = `*==============================================================================*
* Hydrodynamic Component Input Data                                            *
*==============================================================================*
*
`;
        
        nodes.forEach(node => {
            if (node.data?.componentType) {
                output += this.generateComponent(node);
            }
        });

        edges.forEach(edge => {
            output += this.generateJunction(edge, nodes);
        });

        return output;
    }

    generateComponent(node) {
        const componentType = node.data.componentType;
        const componentProps = node.data.componentProp || {};
        const componentId = this.getComponentId(node.id);
        const componentName = node.data.label || `comp_${node.id}`;

        switch (componentType) {
            case 'PIPE':
                return this.generatePipeComponent(componentId, componentName, componentProps);
            case 'SNGLVOL':
                return this.generateSnglvolComponent(componentId, componentName, componentProps);
            case 'TMDPVOL':
                return this.generateTmdpvolComponent(componentId, componentName, componentProps);
            default:
                return `* Component ${componentId}: ${componentName} (${componentType})\n*\n`;
        }
    }

    generatePipeComponent(componentId, name, props) {
        const nv = props.numberOfVolumes || 1;
        
        let output = `*------------------------------------------------------------------------------*
* Component ${componentId}: ${name} (PIPE)
*------------------------------------------------------------------------------*
${componentId}0000  ${name}  pipe
${componentId}0001  ${nv}
`;

        // 면적 데이터
        for (let i = 1; i <= nv; i++) {
            const area = props.xAreaTable?.[i-1]?.area || 0.30;
            output += `${componentId}01${String(i).padStart(2, '0')}  ${area}      ${i}\n`;
        }

        // 길이 데이터
        for (let i = 1; i <= nv; i++) {
            const length = props.xLengthTable?.[i-1]?.length || 1.0;
            output += `${componentId}03${String(i).padStart(2, '0')}  ${length}       ${i}\n`;
        }

        output += `*\n`;
        return output;
    }

    generateSnglvolComponent(componentId, name, props) {
        return `*------------------------------------------------------------------------------*
* Component ${componentId}: ${name} (SNGLVOL)
*------------------------------------------------------------------------------*
${componentId}0000  ${name}  snglvol
${componentId}0101  ${props.area || 1.0}   ${props.length || 1.0}  ${props.volume || 0.0}  0.0  0.0  0.0
${componentId}0200  3   ${props.pressure || 1.5e6}    ${props.temperature || 573.15}  0.0  0.0  0.0
*
`;
    }

    generateTmdpvolComponent(componentId, name, props) {
        let output = `*------------------------------------------------------------------------------*
* Component ${componentId}: ${name} (TMDPVOL)
*------------------------------------------------------------------------------*
${componentId}0000  ${name}  tmdpvol
${componentId}0101  ${props.area || 1.0}   ${props.length || 1.0}  0.0  0.0  0.0  0.0
*
`;

        const timePoints = props.timeTable || [{ time: 0.0, pressure: 1.5e6, temperature: 573.15, quality: 0.0 }];
        output += `${componentId}0200  ${String(timePoints.length).padStart(3, '0')}\n`;
        
        timePoints.forEach(point => {
            output += `${componentId}0201  ${point.time}  ${point.pressure}    ${point.temperature}   ${point.quality}\n`;
        });

        output += `*\n`;
        return output;
    }

    generateJunction(edge, nodes) {
        const junctionId = this.getJunctionId(edge.id);
        const sourceCompId = this.getComponentId(edge.source);
        const targetCompId = this.getComponentId(edge.target);
        
        return `*------------------------------------------------------------------------------*
* Junction ${junctionId}
*------------------------------------------------------------------------------*
${junctionId}0000 jcn  sngljun
${junctionId}0101  ${sourceCompId}010002  ${targetCompId}010001  ${edge.data?.area || 0.30}  0.0  0.0  000000
*
`;
    }

    generateEndCard() {
        return `*==============================================================================*
* End of Input                                                                 *
*==============================================================================*
.
`;
    }

    getComponentId(nodeId) {
        const numericId = nodeId.replace(/\D/g, '').slice(-3).padStart(3, '0');
        return `1${numericId}`;
    }

    getJunctionId(edgeId) {
        const numericId = edgeId.replace(/\D/g, '').slice(-3).padStart(3, '0');
        return `2${numericId}`;
    }
}

// 테스트 실행
console.log('🚀 SMART.i 파일 생성기 테스트 시작...\n');

const generator = new TestSmartFileGenerator();
const smartFileContent = generator.generateSmartFile(mockFlowData);

console.log('📄 생성된 SMART.i 파일 내용:');
console.log('='.repeat(80));
console.log(smartFileContent);
console.log('='.repeat(80));

// 파일로 저장
const outputPath = path.join(__dirname, 'test_output.i');
fs.writeFileSync(outputPath, smartFileContent, 'utf8');

console.log(`\n✅ 테스트 완료! 파일이 다음 위치에 저장되었습니다:`);
console.log(`📁 ${outputPath}`);

// 기본 검증
const lines = smartFileContent.split('\n');
const hasRequiredCards = {
    card100: lines.some(line => line.startsWith('100')),
    card101: lines.some(line => line.startsWith('101')),
    card102: lines.some(line => line.startsWith('102')),
    card110: lines.some(line => line.startsWith('110')),
    monitoring: lines.some(line => line.startsWith('301')),
    components: lines.some(line => line.includes('0000') && line.includes('pipe')),
    endCard: lines.some(line => line.trim() === '.')
};

console.log('\n🔍 기본 검증 결과:');
Object.entries(hasRequiredCards).forEach(([key, value]) => {
    console.log(`  ${value ? '✅' : '❌'} ${key}: ${value ? 'OK' : 'MISSING'}`);
});

const nodeCount = mockFlowData.nodes.length;
const edgeCount = mockFlowData.edges.length;
console.log(`\n📊 통계:`);
console.log(`  노드 수: ${nodeCount}`);
console.log(`  엣지 수: ${edgeCount}`);
console.log(`  총 라인 수: ${lines.length}`);
console.log(`  파일 크기: ${Buffer.byteLength(smartFileContent, 'utf8')} bytes`);

console.log('\n🎉 테스트 완료!');