/**
 * SMART.i 입력 파일 생성기
 * 스토어에 저장된 노드 데이터를 MARS-KS T/H 코드용 SMART.i 형식으로 변환
 */

import { componentTypes } from '../components/node-editor/ComponentsType.jsx';

class SmartFileGenerator {
    constructor() {
        this.cardCounter = 100; // 카드 번호 시작값
        this.componentCounter = 100; // 컴포넌트 번호 시작값 (100, 110, 120, ...)
    }

    /**
     * 스토어 데이터를 SMART.i 파일로 변환
     * @param {Object} flowData - useFlowStore의 present 데이터 {nodes, edges}
     * @returns {string} SMART.i 형식의 문자열
     */
    generateSmartFile(flowData) {
        const { nodes, edges } = flowData;
        
        let output = this.generateHeader();
        output += this.generateControlCards();
        output += this.generateTimeCards();
        output += this.generateMonitoringCards(nodes);
        output += this.generateTripCards();
        output += this.generateHydrodynamicComponents(nodes, edges);
        output += this.generateHeatStructures(nodes);
        output += this.generateTables(nodes);
        output += this.generateEndCard();
        
        return output;
    }

    /**
     * 헤더 정보 생성
     */
    generateHeader() {
        const date = new Date();
        const dateStr = date.toLocaleDateString('ko-KR');
        
        return `*===*===*==*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*
=             SMART365 Steady-State Input Deck for MARS-KS T/H Code             =
*===*===*==*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*===*
*
* Generated by System Editor on ${dateStr}
* 🤖 Generated with Claude Code (https://claude.ai/code)
*
*==============================================================================*
* Miscellaneous Control Cards                                                 *
*==============================================================================*
`;
    }

    /**
     * 기본 제어 카드 생성 (100-120번대)
     */
    generateControlCards() {
        return `*------------------------------------------------------------------------------*
* Card 100 : Problem Type and Options                                          *
*------------------------------------------------------------------------------*
*     type      options
100   new       transnt
*
*------------------------------------------------------------------------------*
* Card 101 : Input Check and Run Option                                        *
*------------------------------------------------------------------------------*
*     option
101   run
*
*------------------------------------------------------------------------------*
* Card 102 : Unit Selection                                                    *
*------------------------------------------------------------------------------*
*     input     output
102   si        si
*
*------------------------------------------------------------------------------*
* Card 110 : Noncondensable Gas Species                                        *
*------------------------------------------------------------------------------*
*     gas type
110   nitrogen
*
*------------------------------------------------------------------------------*
* Card 115 : Time Step Size                                                    *
*------------------------------------------------------------------------------*
115   1.0
*
*------------------------------------------------------------------------------*
* Card 120 : Reference Component                                               *
*------------------------------------------------------------------------------*
*     component     value      fluid    name
120   110010000     0.7965     h2o      pri-sys
*
`;
    }

    /**
     * 시간 제어 카드 생성 (200번대)
     */
    generateTimeCards() {
        return `*==============================================================================*
* Time Step Control Cards                                                      *
*==============================================================================*
*
*     time  min-dt    max-dt    edit  minor   major    restart
200   0.0
201   100.0  1.0e-8   0.001    00019  1000    10000    100000
202   5000.0 1.0e-8   0.01     00019  100     50000    500000
*
`;
    }

    /**
     * 모니터링 변수 카드 생성 (300번대)
     */
    generateMonitoringCards(nodes) {
        let output = `*==============================================================================*
* Minor Edit Data                                                              *
*==============================================================================*
*
`;
        
        let cardNum = 301;
        let groupNum = 1;
        
        // 노드별 모니터링 변수 생성
        nodes.forEach(node => {
            if (node.data?.componentType) {
                const componentId = this.getComponentId(node.id);
                
                // 압력 모니터링
                output += `${cardNum}  p        ${componentId}010000   13.e6     17.e6     ${groupNum}     1     *${node.data.label || node.id} pressure\n`;
                cardNum++;
                
                // 온도 모니터링
                output += `${cardNum}  tempf    ${componentId}010000   520.0     640.0     ${groupNum}     2     *${node.data.label || node.id} temperature\n`;
                cardNum++;
                
                // 유량 모니터링 (PIPE, SNGLJUN 등)
                if (['PIPE', 'SNGLJUN'].includes(node.data.componentType)) {
                    output += `${cardNum}  mflowj   ${componentId}000000   0.0       3000.0    ${groupNum}     3     *${node.data.label || node.id} flow\n`;
                    cardNum++;
                }
                
                groupNum++;
            }
        });

        return output;
    }

    /**
     * 트립 카드 생성 (400-500번대)
     */
    generateTripCards() {
        return `*==============================================================================*
* Input Trip Data                                                              *
*==============================================================================*
*
*-----*-----*-----*-----*-----*-----*-----*-----*-----*-----*-----*-----*------*
* Variable Trip Cards                                                           *
*-----*-----*-----*-----*-----*-----*-----*-----*-----*-----*-----*-----*------*
*
401  time   0   gt   null     0     1.0e6    l  -1.0   "Always false"
402  time   0   gt   null     0     0.0      l  -1.0   "Always true"
*
`;
    }

    /**
     * 유체역학 컴포넌트 생성
     */
    generateHydrodynamicComponents(nodes, edges) {
        let output = `*==============================================================================*
* Hydrodynamic Component Input Data                                            *
*==============================================================================*
*
`;
        
        nodes.forEach(node => {
            if (node.data?.componentType) {
                output += this.generateComponent(node);
            }
        });

        // 접합부 생성 (edges 기반)
        edges.forEach(edge => {
            output += this.generateJunction(edge, nodes);
        });

        return output;
    }

    /**
     * 개별 컴포넌트 생성
     */
    generateComponent(node) {
        const componentType = node.data.componentType;
        const componentProps = node.data.componentProp || {};
        const componentId = this.getComponentId(node.id);
        const componentName = node.data.label || `comp_${node.id}`;

        switch (componentType) {
            case 'PIPE':
                return this.generatePipeComponent(componentId, componentName, componentProps);
            case 'SNGLVOL':
                return this.generateSnglvolComponent(componentId, componentName, componentProps);
            case 'TMDPVOL':
                return this.generateTmdpvolComponent(componentId, componentName, componentProps);
            case 'HTSTR':
                return this.generateHeatStructure(componentId, componentName, componentProps);
            default:
                return this.generateGenericComponent(componentId, componentName, componentType, componentProps);
        }
    }

    /**
     * PIPE 컴포넌트 생성
     */
    generatePipeComponent(componentId, name, props) {
        const nv = props.numberOfVolumes || 1;
        
        let output = `*------------------------------------------------------------------------------*
* Component ${componentId}: ${name} (PIPE)
*------------------------------------------------------------------------------*
${componentId}0000  ${name}  pipe
${componentId}0001  ${nv}
`;

        // 면적 데이터 (CCC0101-0199)
        if (props.xAreaTable && props.xAreaTable.length > 0) {
            props.xAreaTable.forEach((row, index) => {
                output += `${componentId}01${String(index + 1).padStart(2, '0')}  ${row.area || 0.30}      ${index + 1}\n`;
            });
        } else {
            // 기본값 생성
            for (let i = 1; i <= nv; i++) {
                output += `${componentId}01${String(i).padStart(2, '0')}  0.30      ${i}\n`;
            }
        }

        // 길이 데이터 (CCC0301-0399)
        if (props.xLengthTable && props.xLengthTable.length > 0) {
            props.xLengthTable.forEach((row, index) => {
                output += `${componentId}03${String(index + 1).padStart(2, '0')}  ${row.length || 1.0}      ${index + 1}\n`;
            });
        } else {
            // 기본값 생성
            for (let i = 1; i <= nv; i++) {
                output += `${componentId}03${String(i).padStart(2, '0')}  1.0       ${i}\n`;
            }
        }

        // 체적 데이터 (CCC0401-0499) - 선택사항이므로 0으로 설정
        for (let i = 1; i <= nv; i++) {
            output += `${componentId}04${String(i).padStart(2, '0')}  0.0       ${i}\n`;
        }

        // 수직각 데이터 (CCC0601-0699)
        if (props.verticalAngleTable && props.verticalAngleTable.length > 0) {
            props.verticalAngleTable.forEach((row, index) => {
                output += `${componentId}06${String(index + 1).padStart(2, '0')}  ${row.verticalAngle || 0.0}     ${index + 1}\n`;
            });
        } else {
            // 기본값 생성
            for (let i = 1; i <= nv; i++) {
                output += `${componentId}06${String(i).padStart(2, '0')}  0.0       ${i}\n`;
            }
        }

        // 마찰 데이터 (CCC0801-0899)
        if (props.frictionTable && props.frictionTable.length > 0) {
            props.frictionTable.forEach((row, index) => {
                output += `${componentId}08${String(index + 1).padStart(2, '0')}  ${row.roughness || 0.0001}  ${row.hydraulicDiameter || 0.0}   ${index + 1}\n`;
            });
        } else {
            // 기본값 생성
            for (let i = 1; i <= nv; i++) {
                output += `${componentId}08${String(i).padStart(2, '0')}  0.0001  0.0   ${i}\n`;
            }
        }

        // 제어 플래그 (CCC1001-1099)
        if (props.volumeFlagsTable && props.volumeFlagsTable.length > 0) {
            props.volumeFlagsTable.forEach((row, index) => {
                const flags = this.generateVolumeFlags(row.volumeFlags || {});
                output += `${componentId}10${String(index + 1).padStart(2, '0')}  ${flags}     ${index + 1}\n`;
            });
        } else {
            // 기본값 생성
            for (let i = 1; i <= nv; i++) {
                output += `${componentId}10${String(i).padStart(2, '0')}  00000     ${i}\n`;
            }
        }

        // 접합부 제어 플래그 (CCC1101-1199)
        if (nv > 1) {
            for (let i = 1; i < nv; i++) {
                output += `${componentId}11${String(i).padStart(2, '0')}  000000    ${i}\n`;
            }
        }

        // 초기 조건 (CCC1201-1299)
        if (props.initialCondTable && props.initialCondTable.length > 0) {
            props.initialCondTable.forEach((row, index) => {
                const type = row.thermoState || '3';
                let conditionLine = `${componentId}12${String(index + 1).padStart(2, '0')}  ${type}   ${row.initialValue1 || 1.5e6}    ${row.initialValue2 || 573.15}`;
                
                if (['0', '4', '5', '6'].includes(type) && row.initialValue3) {
                    conditionLine += `  ${row.initialValue3}`;
                }
                if (['0', '6'].includes(type) && row.initialValue4) {
                    conditionLine += `  ${row.initialValue4}`;
                }
                if (type === '6' && row.initialValue5) {
                    conditionLine += `  ${row.initialValue5}`;
                }
                
                conditionLine += `   ${index + 1}\n`;
                output += conditionLine;
            });
        } else {
            // 기본값 생성 (압력, 온도)
            for (let i = 1; i <= nv; i++) {
                output += `${componentId}12${String(i).padStart(2, '0')}  3   1.5e6    573.15  0.0  0.0  0.0   ${i}\n`;
            }
        }

        // 접합부 초기 조건 (CCC1300, CCC1301-1399)
        if (nv > 1) {
            output += `${componentId}1300  0\n`; // 속도 입력 모드
            for (let i = 1; i < nv; i++) {
                output += `${componentId}13${String(i).padStart(2, '0')}  0.0  0.0  0.0  ${i}\n`;
            }
        }

        output += `*\n`;
        return output;
    }

    /**
     * SNGLVOL 컴포넌트 생성
     */
    generateSnglvolComponent(componentId, name, props) {
        return `*------------------------------------------------------------------------------*
* Component ${componentId}: ${name} (SNGLVOL)
*------------------------------------------------------------------------------*
${componentId}0000  ${name}  snglvol
${componentId}0101  ${props.area || 1.0}   ${props.length || 1.0}  ${props.volume || 0.0}  ${props.azimuthalAngle || 0.0}  ${props.verticalAngle || 0.0}  ${props.elevationChange || 0.0}
${componentId}0102  ${props.roughness || 0.0001}  ${props.hydraulicDiameter || 0.0}  ${props.flags || '00000'}
${componentId}0200  ${props.thermoState || '3'}   ${props.pressure || 1.5e6}    ${props.temperature || 573.15}  0.0  0.0  0.0
*
`;
    }

    /**
     * TMDPVOL 컴포넌트 생성
     */
    generateTmdpvolComponent(componentId, name, props) {
        let output = `*------------------------------------------------------------------------------*
* Component ${componentId}: ${name} (TMDPVOL)
*------------------------------------------------------------------------------*
${componentId}0000  ${name}  tmdpvol
${componentId}0101  ${props.area || 1.0}   ${props.length || 1.0}  ${props.volume || 0.0}  ${props.azimuthalAngle || 0.0}  ${props.verticalAngle || 0.0}  ${props.elevationChange || 0.0}
${componentId}0102  ${props.roughness || 0.0001}  ${props.hydraulicDiameter || 0.0}  ${props.flags || '00000'}
*
`;

        // 시간 의존적 데이터 테이블
        const timePoints = props.timeTable || [{ time: 0.0 }, { time: 1000.0 }];
        output += `${componentId}0200  ${String(timePoints.length).padStart(3, '0')}\n`;
        
        timePoints.forEach(point => {
            output += `${componentId}0201  ${point.time || 0.0}  ${point.pressure || 1.5e6}    ${point.temperature || 573.15}   ${point.quality || 0.0}\n`;
        });

        output += `*\n`;
        return output;
    }

    /**
     * 열구조체 생성
     */
    generateHeatStructures(nodes) {
        let output = `*==============================================================================*
* Heat Structure Input Data                                                    *
*==============================================================================*
*
`;
        
        nodes.forEach(node => {
            if (node.data?.componentType === 'HTSTR') {
                const componentId = this.getComponentId(node.id);
                const props = node.data.componentProp || {};
                
                output += `*------------------------------------------------------------------------------*
* Heat Structure ${componentId}: ${node.data.label || node.id}
*------------------------------------------------------------------------------*
1${componentId}1000  ${props.numberOfAxialNodes || 10}     ${props.numberOfRadialNodes || 2}    ${props.geometry || 1}    0    0.0
1${componentId}1100  ${props.meshFormat || 0}      ${props.numberOfRadialNodes || 2}
1${componentId}1101  ${props.meshInterval || 0.001}  1    
1${componentId}1201  ${props.materialNumber || 3}    1
1${componentId}1301  ${props.sourceMultiplier || 1.0}   1
1${componentId}1400  ${props.initialTemperature || 0}           
1${componentId}1401  ${props.initialTempValue || 573.15}      2
*
1${componentId}1501  ${props.leftBoundaryComp || '110010000'}  ${props.leftBoundaryType || 10000}  ${props.leftBoundaryIncrement || 100}   0    ${props.leftBoundaryArea || 0.12}   ${props.leftBoundaryNodes || 10}
*
1${componentId}1601  ${props.rightBoundaryHeatFlux || -500}           0  ${props.rightBoundaryTemp || 1500}   0    ${props.rightBoundaryArea || 0.12}   ${props.rightBoundaryNodes || 10} 
*
1${componentId}1701  0   0.1   0.     0.   ${props.rightBoundaryNodes || 10}
*
1${componentId}1800  0                                                   
1${componentId}1801  ${props.heatTransferCoeff || 6.180387e-1}   0.5  0.5   0.   0.  0.  0.  1.   ${props.leftBoundaryNodes || 10}
1${componentId}1900  0                                                   
1${componentId}1901  ${props.heatTransferCoeff || 6.180387e-1}   0.5  0.5   0.   0.  0.  0.  1.   ${props.rightBoundaryNodes || 10}
*
`;
            }
        });

        return output;
    }

    /**
     * 접합부 생성
     */
    generateJunction(edge, nodes) {
        const sourceNode = nodes.find(n => n.id === edge.source);
        const targetNode = nodes.find(n => n.id === edge.target);
        
        if (!sourceNode || !targetNode) return '';
        
        const junctionId = this.getJunctionId(edge.id);
        const sourceCompId = this.getComponentId(edge.source);
        const targetCompId = this.getComponentId(edge.target);
        
        return `*------------------------------------------------------------------------------*
* Junction ${junctionId}: ${sourceNode.data?.label || edge.source} to ${targetNode.data?.label || edge.target}
*------------------------------------------------------------------------------*
${junctionId}0000 jcn-${edge.id.slice(-4)}  sngljun
${junctionId}0101  ${sourceCompId}010002  ${targetCompId}010001  ${edge.data?.area || 0.010}  0.05  0.05  000000
${junctionId}0201  1    0.0  0.0  0.0
*
`;
    }

    /**
     * 테이블 데이터 생성
     */
    generateTables(nodes) {
        let output = `*==============================================================================*
* General Table Data                                                           *
*==============================================================================*
*
`;
        
        // 기본 온도 테이블
        output += `20250000 temp
20250001    0.0       573.15
20250002 100000.      573.15
*
`;

        // 열구조체 재료 물성 테이블
        output += `*==============================================================================*
* Heat Structure Thermal Property Data                                         *
*==============================================================================*
*
*------------------------------------------------------------------------------*
* Material 3: Steel
*------------------------------------------------------------------------------*
*             temp (k)   volumetric heat capacity (j/m3.k)
20100300   tbl/fctn         1                      1
20100351    273.15       3.445882e+06
20100352    573.15       3.613069e+06
20100353    873.15       3.753589e+06
*             temp (k)   thermal conductivity (w/m.k)
20100301    273.15      50.0
20100302    573.15      40.0
20100303    873.15      30.0
*
`;

        return output;
    }

    /**
     * 종료 카드 생성
     */
    generateEndCard() {
        return `*==============================================================================*
* End of Input                                                                 *
*==============================================================================*
.
`;
    }

    /**
     * 유틸리티 함수들
     */
    getComponentId(nodeId) {
        // 노드 ID를 숫자 컴포넌트 ID로 변환 (예: "node_123" -> "123")
        const numericId = nodeId.replace(/\D/g, '').slice(-3).padStart(3, '0');
        return `1${numericId}`;
    }

    getJunctionId(edgeId) {
        // 엣지 ID를 숫자 접합부 ID로 변환
        const numericId = edgeId.replace(/\D/g, '').slice(-3).padStart(3, '0');
        return `2${numericId}`;
    }

    generateVolumeFlags(flags = {}) {
        return `${flags.tFlag || '0'}${flags.lFlag || '0'}${flags.pFlag || '0'}${flags.vFlag || '0'}${flags.bFlag || '0'}${flags.fFlag || '0'}${flags.eFlag || '0'}`;
    }

    generateJunctionFlags(flags = {}) {
        return `0${flags.eFlag || '0'}${flags.fFlag || '0'}0${flags.cFlag || '0'}${flags.aFlag || '0'}${flags.hFlag || '0'}${flags.sFlag || '0'}`;
    }

    generateGenericComponent(componentId, name, type, props) {
        return `*------------------------------------------------------------------------------*
* Component ${componentId}: ${name} (${type})
*------------------------------------------------------------------------------*
${componentId}0000  ${name}  ${type.toLowerCase()}
* ${type} component properties would go here
* Component props: ${JSON.stringify(props, null, 2).split('\n').map(line => `* ${line}`).join('\n')}
*
`;
    }
}

// Export default instance
export default new SmartFileGenerator();

/**
 * 사용 예시:
 * 
 * import smartFileGenerator from './utils/smartFileGenerator.js';
 * import { useFlowStore } from './components/store/useFlowStore.jsx';
 * 
 * // 스토어에서 현재 데이터 가져오기
 * const flowData = useFlowStore.getState().present;
 * 
 * // SMART.i 파일 생성
 * const smartFileContent = smartFileGenerator.generateSmartFile(flowData);
 * 
 * // 파일 다운로드 또는 저장
 * const blob = new Blob([smartFileContent], { type: 'text/plain' });
 * const url = URL.createObjectURL(blob);
 * const link = document.createElement('a');
 * link.href = url;
 * link.download = 'generated_smart_input.i';
 * link.click();
 */